version: '3.8'
services:

  wj-frontend:
    build:
      context: wj-frontend
      dockerfile: Dockerfile
      args:
        VITE_OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
        VITE_OKTA_ISSUER: ${OKTA_ISSUER}
        VITE_REDIRECT_URI: http://localhost:3000/login/callback
        VITE_API_ADDRESS: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - wj-db
      - wj-backend
    restart: always
    networks:
      - workout-journal-network

  wj-backend:
    build:
      context: wj-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - wj-db
    environment:
      ALLOWED_ORIGINS: http://localhost:3000
      DATASOURCE_HOSTNAME: wj-db
      DATASOURCE_PORT: 3306
      DATASOURCE_DB_NAME: workout-journal-db
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: userpass
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_ISSUER: ${OKTA_ISSUER}
    networks:
      - workout-journal-network

  wj-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: workout-journal-db
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
      - ./wj-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - workout-journal-network

volumes:
  mysql-database-data-volume:
networks:
  workout-journal-network:




